#!/bin/sh

IMAGE_OK=$(docker images|grep inabox|cut -f 1 -d ' ')
if [ "$IMAGE_OK" != "inabox" ]; then
    echo "Building container image..."
    docker-compose -f container/docker-compose.yaml build
fi

IMAGE_OK=$(docker images|grep inabox|cut -f 1 -d ' ')
if [ "$IMAGE_OK" == "inabox" ]; then
    #echo "Run 'ssh -p 2222 inabox@localhost' to enter..."
    wssh --port=4001 --policy=reject &!
    echo "webssh running in http://localhost:4001"
    python inabox-switchboard.py
    killall wssh
else
    echo "Cannot find docker image. Run docker-compose in container folder"
fi
